Trending topics
SpaceyaTech/Team-Rio-React pull request #20
Opened 2022-11-08 14:11 UTC by Ebenezr

Trending topics component, done

2022-11-09 14:53 UTC, nyandika requested changes
- Place the dummy data in a data folder in the root, and then call it from there.
- To further move it as close to the live experience place it in a json file and then serve it via http. something like [json-server](https://www.npmjs.com/package/json-server)
- Create an interface/type of data and then use this to statically type your fields
- I think you have to restructure this components a bit more

2022-11-09 14:53 UTC, nyandika commented on src/components/ArticlelCards.tsx
> +const ArticlelCards = () => {
typo

2022-11-09 14:53 UTC, nyandika commented on src/components/Articles/ArticlelCards.tsx
> +const ArticlelCards = () => {
why do we have 2 similarly named components?

2022-11-10 08:41 UTC, Ebenezr commented
noted, then on server fetching data any preference state manager or just a simple axios fetch

2022-11-10 09:11 UTC, nyandika commented
> noted, then on server fetching data any preference state manager or just a simple axios fetch

axios is fine

2022-11-16 14:09 UTC, closed without merging