Articles component
SpaceyaTech/Team-Rio-React pull request #26
Opened 2022-11-16 14:00 UTC by Ebenezr

![image](https://user-images.githubusercontent.com/37300065/202200465-6a3f62b2-29a6-449b-87b6-dc48b4b4b878.png)

2022-11-17 09:12 UTC, nyandika requested changes
You should also commit the package-lock file

I also noticed you deleted the other PR to create a new one, you dont have to do this. making changes on the same branch and pushing to the same branch will automatically update the PR. let me know if you need further help on that and we can setup a small sync

2022-11-17 09:12 UTC, nyandika commented on src/components/Articles/BlogCards.tsx
> +const BlogCards: React.FC = () => {
This is not a recommended way of creating components. it's been removed from template actually:  [Link](https://github.com/facebook/create-react-app/pull/8177)

2022-11-17 09:12 UTC, nyandika commented on src/components/Articles/BlogCards.tsx
> +const BlogCards: React.FC = () => {
you can use: `const Blogcard = () => {}`

2022-11-17 09:12 UTC, nyandika commented on src/components/Articles/BlogCards.tsx
> +    getArticles().then((response) => setArticles(response?.data));
You can handle all fetching and parsing in the `getArticles` method and just get the data here

2022-11-17 13:00 UTC, Ebenezr commented
noted

2022-11-17 19:40 UTC, nyandika commented on src/components/Articles/BlogCards.tsx
> +    getArticles().then((response) => setArticles(response?.data));
Yea this is perfect

2022-11-18 10:07 UTC, nyandika approved these changes
There are a couple of nits that we could refactor as we go but this is good progress

2022-11-28 17:01 UTC, nyandika commented
I pushed some updates to lib dependencies which had led to conflicts on this branch. Let me know if you need help resolving this. I can set up a sync

2022-11-29 11:06 UTC, closed without merging

2022-11-29 11:30 UTC, Ebenezr commented
![image](https://user-images.githubusercontent.com/37300065/204517529-3691c46a-bb92-48fc-85fb-1321e67e24d3.png)

I have fixed the conflicts, but I'm version error when I try to npm install, 
NB: I have updated my node and npm to the latest version already.